services:
  - type: web
    name: expense-ai
    env: python
    buildCommand: pip install -r expense_ai/requirements.txt
    startCommand: cd expense_ai && gunicorn --bind 0.0.0.0:$PORT api_server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
