services:
  - type: web
    name: expense-ai-backend
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api_server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: GEMINI_API_KEY
        value: AIzaSyBF7jxAXLiAQhmR8UzFBPT9tTcNmQGihhw
